### ISSUE TITLE
Request for Icon Enhancement: Adorning Vencord with Noble Insignias

### ISSUE THREAD

**Issue by TheLovinator1** [KillYoy/DiscordNight#54]
Hark, my liege,

Methinks I have ventured upon the digital realm known as Vencord, and lo, I have noticed a peculiar absence of icons adorning its visage. Verily, it is akin to a knight without his noble sigil, a tapestry devoid of its vibrant hues.

I beseech thee, O gracious sovereign, to bestow upon Vencord the regal splendor it deserves. Grant it icons, resplendent and gallant, that they may grace its countenance as our coats of arms adorn our armor. 

```css
.vc-settings::before { /* Like BetterDiscord settings. */
    background: url("") !important;
    background-repeat: no-repeat !important;
}
.vc-plugins::before { /* Like BetterDiscord plugins. */
    background: url("") !important;
    background-repeat: no-repeat !important;
}
.vc-themes::before { /* Like BetterDiscord themes. */
    background: url("") !important;
    background-repeat: no-repeat !important;
}
.vc-updater::before { /* Toggle auto update, get notified about new updates, etc. */
    background: url("") !important;
    background-repeat: no-repeat !important;
}
.vc-cloud::before { /* Sync settings to the cloud. */
    background: url("") !important;
    background-repeat: no-repeat !important;
}
.vc-backup-restore::before { /* Import/export settings to a JSON file. */
    background: url("") !important;
    background-repeat: no-repeat !important;
}
```

Yours in loyal service,
Ser Lovinator, the Devoted
