### ISSUE TITLE
Title bar margin issue

### ISSUE THREAD

**Issue by logie-labs** [KillYoy/DiscordNight#70]
I've had to change the CSS so I can drag around my window properly because before the top 4px where margin instead of padding, this breaks the user-drag for electron.

```css
@import url("https://KillYoy.github.io/DiscordNight/DiscordNight.css");

.titleBar__421ed {
    margin: 0 !important;
    padding-top: 4px !important;
}
```

![Image](https://github.com/user-attachments/assets/3f8c3aba-eb93-4094-9f73-fe6970ede8e2)
